version: '3'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=base_nest
    volumes:
      - ./.docker/postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "root",
          "-d",
          "base_nest"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
 